// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: user.proto

package user

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	common "github.com/kickastone/trpc-demo/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccountByUserNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByUserNameRequest) Reset() {
	*x = GetAccountByUserNameRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByUserNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByUserNameRequest) ProtoMessage() {}

func (x *GetAccountByUserNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByUserNameRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByUserNameRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountByUserNameRequest) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetAccountByUserNameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetAccountByUserNameResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	ErrCode       int32                              `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg        string                             `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Data          *GetAccountByUserNameResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByUserNameResponse) Reset() {
	*x = GetAccountByUserNameResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByUserNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByUserNameResponse) ProtoMessage() {}

func (x *GetAccountByUserNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByUserNameResponse.ProtoReflect.Descriptor instead.
func (*GetAccountByUserNameResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountByUserNameResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *GetAccountByUserNameResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *GetAccountByUserNameResponse) GetData() *GetAccountByUserNameResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	CreateTsSec   int64                  `protobuf:"varint,5,opt,name=create_ts_sec,json=createTsSec,proto3" json:"create_ts_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetCreateTsSec() int64 {
	if x != nil {
		return x.CreateTsSec
	}
	return 0
}

type GetAccountByUserNameResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserInfo              `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByUserNameResponse_Data) Reset() {
	*x = GetAccountByUserNameResponse_Data{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByUserNameResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByUserNameResponse_Data) ProtoMessage() {}

func (x *GetAccountByUserNameResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByUserNameResponse_Data.ProtoReflect.Descriptor instead.
func (*GetAccountByUserNameResponse_Data) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetAccountByUserNameResponse_Data) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x0etrpc.demo.user\x1a\x15common/metadata.proto\"q\n" +
	"\x1bGetAccountByUserNameRequest\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1a.trpc.demo.common.MetadataR\bmetadata\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\xd8\x01\n" +
	"\x1cGetAccountByUserNameResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12E\n" +
	"\x04data\x18\x03 \x01(\v21.trpc.demo.user.GetAccountByUserNameResponse.DataR\x04data\x1a=\n" +
	"\x04Data\x125\n" +
	"\tuser_info\x18\x01 \x01(\v2\x18.trpc.demo.user.UserInfoR\buserInfo\"\xa4\x01\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\"\n" +
	"\rcreate_ts_sec\x18\x05 \x01(\x03R\vcreateTsSec2y\n" +
	"\x04User\x12q\n" +
	"\x14GetAccountByUserName\x12+.trpc.demo.user.GetAccountByUserNameRequest\x1a,.trpc.demo.user.GetAccountByUserNameResponseB,Z*github.com/kickastone/trpc-demo/proto/userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_proto_goTypes = []any{
	(*GetAccountByUserNameRequest)(nil),       // 0: trpc.demo.user.GetAccountByUserNameRequest
	(*GetAccountByUserNameResponse)(nil),      // 1: trpc.demo.user.GetAccountByUserNameResponse
	(*UserInfo)(nil),                          // 2: trpc.demo.user.UserInfo
	(*GetAccountByUserNameResponse_Data)(nil), // 3: trpc.demo.user.GetAccountByUserNameResponse.Data
	(*common.Metadata)(nil),                   // 4: trpc.demo.common.Metadata
}
var file_user_proto_depIdxs = []int32{
	4, // 0: trpc.demo.user.GetAccountByUserNameRequest.metadata:type_name -> trpc.demo.common.Metadata
	3, // 1: trpc.demo.user.GetAccountByUserNameResponse.data:type_name -> trpc.demo.user.GetAccountByUserNameResponse.Data
	2, // 2: trpc.demo.user.GetAccountByUserNameResponse.Data.user_info:type_name -> trpc.demo.user.UserInfo
	0, // 3: trpc.demo.user.User.GetAccountByUserName:input_type -> trpc.demo.user.GetAccountByUserNameRequest
	1, // 4: trpc.demo.user.User.GetAccountByUserName:output_type -> trpc.demo.user.GetAccountByUserNameResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
